# Generated by Django 6.0.4 on 2026-05-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbon',
            new_name='isbn',
        ),
    ]
